DreamHacker: CppTimer Class Reference
CppTimer Class Reference abstract
#include <CppTimer.h>
Public Member Functions
CppTimer (const int signo=SIGRTMIN)
virtual void startns (long nanosecs, cppTimerType_t type=PERIODIC)
virtual void startms (long millisecs, cppTimerType_t type=PERIODIC)
virtual void stop ()
virtual ~CppTimer ()
Protected Member Functions
virtual void timerEvent ()=0
Static Private Member Functions
static void handler (int, siginfo_t *si, void *)
Private Attributes
timer_t timerid = 0
struct sigevent sev
struct sigaction sa
struct itimerspec its
Detailed Description
Timer class which repeatedly fires. It's wrapper around the POSIX per-process timer.
Definition at line 34 of file CppTimer.h.
Constructor & Destructor Documentation
CppTimer()
CppTimer::CppTimer (const int signo = SIGRTMIN)
Creates an instance of the timer and connects the signal handler to the timer. The default signal which is being used is SIGRTMIN but can be changed to other signals if other processes / threads use them.
Parameters
signo The signal used by the timer.
GNU GENERAL PUBLIC LICENSE Version 3, 29 June 2007
(C) 2020-2021, Bernd Porr mail@.nosp@m.bern.nosp@m.porr..nosp@m.me.u.nosp@m.k
This is inspired by the timer_create man page.
Definition at line 12 of file CppTimer.cpp.
 {
     // We create a static handler catches the signal SIG
     sa.sa_flags = SA_SIGINFO;
     sa.sa_sigaction = handler;
     sigemptyset(&sa.sa_mask);
     if (sigaction(signo, &sa, NULL) == -1)
         throw("Could not create signal handler");
     // Create the timer
     sev.sigev_notify = SIGEV_SIGNAL;
     sev.sigev_signo = signo;
     // Cruical is that the signal carries the pointer to this class instance here
     // because the handler just handles anything that comes in!
     sev.sigev_value.sival_ptr = this;
     // create the timer
     if (timer_create(CLOCKID, &sev, &timerid) == -1)
         throw("Could not create timer");
 }
References CLOCKID, handler(), sa, sev, and timerid.
~CppTimer()
CppTimer::~CppTimer () virtual
Destructor disarms the timer, deletes it and disconnect the signal handler.
Definition at line 89 of file CppTimer.cpp.
 {
     stop();
     // delete the timer
     timer_delete(timerid);
     // default action for signal handling
     signal(sev.sigev_signo, SIG_IGN);
 }
References sev, stop(), and timerid.
Member Function Documentation
handler()
static void CppTimer::handler (int , siginfo_t * si, void *) inline static private
Definition at line 94 of file CppTimer.h.
     {
         (reinterpret_cast<CppTimer *>(si->si_value.sival_ptr))->timerEvent();
     }
Referenced by CppTimer().
startms()
void CppTimer::startms (long millisecs, cppTimerType_t type = PERIODIC) virtual
Starts the timer. The timer fires first after the specified time in milliseconds and then at that interval in PERIODIC mode. In ONESHOT mode the timer fires once after the specified time in milliseconds.
Parameters
millisecs Time in milliseconds
type Either PERIODIC or ONESHOT
Definition at line 55 of file CppTimer.cpp.
 {
     switch (type)
     {
     case (PERIODIC):
         //starts after specified period of milliseconds
         its.it_value.tv_sec = millisecs / 1000;
         its.it_value.tv_nsec = (millisecs % 1000) * 1000000;
         its.it_interval.tv_sec = millisecs / 1000;
         its.it_interval.tv_nsec = (millisecs % 1000) * 1000000;
         break;
     case (ONESHOT):
         //fires once after specified period of milliseconds
         its.it_value.tv_sec = millisecs / 1000;
         its.it_value.tv_nsec = (millisecs % 1000) * 1000000;
         its.it_interval.tv_sec = 0;
         its.it_interval.tv_nsec = 0;
         break;
     }
     if (timer_settime(timerid, 0, &its, NULL) == -1)
         throw("Could not start timer");
 }
References its, ONESHOT, PERIODIC, and timerid.
Referenced by main().
startns()
void CppTimer::startns (long nanosecs, cppTimerType_t type = PERIODIC) virtual
Starts the timer. The timer fires first after the specified time in nanoseconds and then at that interval in PERIODIC mode. In ONESHOT mode the timer fires once after the specified time in nanoseconds.
Parameters
nanosecs Time in nanoseconds
type Either PERIODIC or ONESHOT
Definition at line 32 of file CppTimer.cpp.
 {
     switch (type)
     {
     case (PERIODIC):
         //starts after specified period of nanoseconds
         its.it_value.tv_sec = nanosecs / 1000000000;
         its.it_value.tv_nsec = nanosecs % 1000000000;
         its.it_interval.tv_sec = nanosecs / 1000000000;
         its.it_interval.tv_nsec = nanosecs % 1000000000;
         break;
     case (ONESHOT):
         //fires once after specified period of nanoseconds
         its.it_value.tv_sec = nanosecs / 1000000000;
         its.it_value.tv_nsec = nanosecs % 1000000000;
         its.it_interval.tv_sec = 0;
         its.it_interval.tv_nsec = 0;
         break;
     }
     if (timer_settime(timerid, 0, &its, NULL) == -1)
         throw("Could not start timer");
 }
References its, ONESHOT, PERIODIC, and timerid.
stop()
void CppTimer::stop () virtual
Stops the timer by disarming it. It can be re-started with start().
Definition at line 78 of file CppTimer.cpp.
 {
     // disarm
     struct itimerspec itsnew;
     itsnew.it_value.tv_sec = 0;
     itsnew.it_value.tv_nsec = 0;
     itsnew.it_interval.tv_sec = 0;
     itsnew.it_interval.tv_nsec = 0;
     timer_settime(timerid, 0, &itsnew, &its);
 }
References its, and timerid.
Referenced by SensorTimer::stopNew(), and ~CppTimer().
timerEvent()
virtual void CppTimer::timerEvent () protected pure virtual
Abstract function which needs to be implemented by the children. This is called every time the timer fires.
Implemented in SensorTimer, and CppTimerCallback.
Field Documentation
its
struct itimerspec CppTimer::its private
Definition at line 89 of file CppTimer.h.
Referenced by startms(), startns(), and stop().
sa
struct sigaction CppTimer::sa private
Definition at line 89 of file CppTimer.h.
Referenced by CppTimer().
sev
struct sigevent CppTimer::sev private
Definition at line 89 of file CppTimer.h.
Referenced by CppTimer(), and ~CppTimer().
timerid
timer_t CppTimer::timerid = 0 private
Definition at line 89 of file CppTimer.h.
Referenced by CppTimer(), startms(), startns(), stop(), and ~CppTimer().
The documentation for this class was generated from the following files:
include/CppTimer.h
src/CppTimer.cpp