DreamHacker: JSONCGIHandler::JSONGenerator Class Reference
JSONCGIHandler::JSONGenerator Class Reference
#include <json_fastcgi_web_api.h>
Public Member Functions
void add (std::string key, std::string value)
void add (std::string key, double value)
void add (std::string key, float value)
void add (std::string key, long value)
void add (std::string key, int value)
std::string getJSON ()
Private Attributes
std::string json = "{"
int firstEntry = 1
Detailed Description
Simple helper function to create a key/value json pairs for the callback function.
Definition at line 70 of file json_fastcgi_web_api.h.
Member Function Documentation
add() [1/5]
void JSONCGIHandler::JSONGenerator::add (std::string key, double value) inline
Adds a JSON entry: double
Parameters
key The JSON key
value The JSON value as a double
Definition at line 91 of file json_fastcgi_web_api.h.
{
             if (!firstEntry) {
                 json = json + ", ";
             }
             json = json + "\"" + key + "\":";
             json = json + std::to_string(value);
             firstEntry = 0;
         }
References firstEntry, and json.
add() [2/5]
void JSONCGIHandler::JSONGenerator::add (std::string key, float value) inline
Adds a JSON entry: float
Parameters
key The JSON key
value The JSON value as a float
Definition at line 105 of file json_fastcgi_web_api.h.
{
             add(key, (double)value);
         }
References add().
add() [3/5]
void JSONCGIHandler::JSONGenerator::add (std::string key, int value) inline
Adds a JSON entry: int
Parameters
key The JSON key
value The JSON value as an int
Definition at line 128 of file json_fastcgi_web_api.h.
{
             add(key, (long)value);
         }
References add().
add() [4/5]
void JSONCGIHandler::JSONGenerator::add (std::string key, long value) inline
Adds a JSON entry: long int
Parameters
key The JSON key
value The JSON value as a long int
Definition at line 114 of file json_fastcgi_web_api.h.
{
             if (!firstEntry) {
                 json = json + ", ";
             }
             json = json + "\"" + key + "\":";
             json = json + std::to_string(value);
             firstEntry = 0;
         }
References firstEntry, and json.
add() [5/5]
void JSONCGIHandler::JSONGenerator::add (std::string key, std::string value) inline
Adds a JSON entry: string
Parameters
key The JSON key
value The JSON value as a string
Definition at line 77 of file json_fastcgi_web_api.h.
{
             if (!firstEntry) {
                 json = json + ", ";
             }
             json = json + "\"" + key + "\":";
             json = json + "\"" + value + "\"";
             firstEntry = 0;
         }
References firstEntry, and json.
Referenced by add(), and JSONCGIADCCallback::getJSONString().
getJSON()
std::string JSONCGIHandler::JSONGenerator::getJSON () inline
Gets the json string
Returns
The JSON data ready to be sent
Definition at line 136 of file json_fastcgi_web_api.h.
 { return json + "}"; }
References json.
Referenced by JSONCGIADCCallback::getJSONString().
Field Documentation
firstEntry
int JSONCGIHandler::JSONGenerator::firstEntry = 1 private
Definition at line 140 of file json_fastcgi_web_api.h.
Referenced by add().
json
std::string JSONCGIHandler::JSONGenerator::json = "{" private
Definition at line 139 of file json_fastcgi_web_api.h.
Referenced by add(), and getJSON().
The documentation for this class was generated from the following file:
include/json_fastcgi_web_api.h