DreamHacker: main/main.cpp File Reference
main.cpp File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <fcntl.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <unistd.h>
#include <stdarg.h>
#include <signal.h>
#include <time.h>
#include <wiringPi.h>
#include <mcp3004.h>
#include <QApplication>
#include "../include/mainwindow.h"
#include "../include/CppTimer.h"
#include <thread>
#include "../include/PulseSensor.h"
#include "../include/json_fastcgi_web_api.h"
Data Structures
class SENSORfastcgicallback
class JSONCGIADCCallback
Functions
void signalHandler (int signum)
void usage (void)
int main (int argc, char *argv[])
Variables
volatile int g_running = 1
Function Documentation
main()
int main (int argc, char * argv[])
Threshold of Beats per minute Modifiable by using ./main -t <int>
bool value: if 1, then ecg will be plotted, if zero ecg will not be plotted Can be changed by giving arguments like this: ./main -g 0 for graph not to be plotted and ./main -g 1 for graph to be plotted. Default is 1
bool value: if 1, then program will run in simulation mode, if 0 then real data of bpm is used. Can be changed by giving arguments like this: ./main -s 0 for real bpm and ./main -g 1 for simulated bpm. Default is 1
bool value if 1, the audio will be played from this progrma itself. Default is 1. can be changed while running the program by giving arguments like ./main -l 0
If we want to play the audio at any time during the day then nightTime should be set to now. For that we need to set this value to 1. This can be done by passing the argument like: ./main -n 1. Default is 0
int value. The delay it takes the program to reach from the state of maybesleep to sleep. Usually it must be half an our but it can be manipulated for testing purpose like this: ./main -w 60 It this example the program would wait for 30 seconds to go from maybesleep state to sleep state.
This variable is used to get the parameters from the terminal
This variable is used to get the parameters from the terminal
Pulse me runs in a c++ timer It reads the analog data from pulse sensor and calculates BPM. BPM is used for other analysis.
Setting up the JSONCGI communication The callback which is called when fastCGI needs data gets a pointer to the SENSOR callback class which contains the samples. Remember this is just a simple example to have access to some data.
The QApplication will form the windows for the display of raw data read from the sensor. This will block the control and the program will keep on runnig stuck here.
If the graphing window is terminated by the user then the control will get stuck in the while loop which depends on the global variable bool runnig
The timer will stop if the control reaches at pulseMe.stop
Definition at line 117 of file main.cpp.
 {
     int threshold = 77;
     bool graph = 1;
     bool simulation = 0;
     bool local_audio = 1;
     bool nightTimeNow = 0;
     int surelySleptTime = 2;
     bool flagSurelySleptTime = 0;
     char key;
     char* value;
     if(argc > 1){
         //mode = atoi(argv[1]);
         for(int i = 1; i < argc; i++){
             if(argv[i][0] == '-'){
                 key = argv[i][1];
                 value = argv[i + 1];
                 switch(key){
                                 case 't':
                                         threshold = atoi(value);
                     i +=1;
                                         break;
                                 case 'g':
                                         graph = atoi(value);
                     i +=1;
                                         break;
                                 case 's':
                                         simulation = atoi(value);
                     i +=1;
                                         break;
                                 case 'l':
                                         local_audio = atoi(value);
                     i +=1;
                                         break;
                                 case 'n':
                                         nightTimeNow = atoi(value);
                     i +=1;
                     break;
                                 case 'w':
                                         surelySleptTime = atoi(value);
                     flagSurelySleptTime = 1;
                     i +=1;
                     break;
                                 case 'h':
                     i +=1;
                     usage();
                     exit(0);
                                         break;
                                 default:
                     printf("Wrong Parameters passed\n\n");
                     usage();
                     exit(0);
                             }
             }else{
                 usage();
                 exit(0);
             }
         }
     }
     signal(SIGINT, signalHandler);
     SensorTimer pulseMe(threshold, simulation, local_audio);
     if(nightTimeNow)
         pulseMe.setNigtTimeToNow();
     //waiting time just after the bpm drops to threshold
     if(flagSurelySleptTime)
         pulseMe.setSurelySleptTime(surelySleptTime);
   SENSORfastcgicallback sensorfastcgicallback;
   pulseMe.setCallback(&sensorfastcgicallback);
   JSONCGIADCCallback fastCGIADCCallback(&sensorfastcgicallback);
     // starting the fastCGI handler with the callback and the
     // socket for nginx.
   JSONCGIHandler* fastCGIHandler = new JSONCGIHandler(&fastCGIADCCallback, NULL, "/tmp/sensorsocket");
     pulseMe.startms(2);
     QApplication a(argc, argv);
     SenseWindow w;
     if(graph){
         w.showMaximized();
         a.exec();
     }
     while(g_running);
    //pulseMe.stop();
    pulseMe.stopNew();
     return 0;
 }//int main(int argc, char *argv[])
References g_running, SensorTimer::setCallback(), SensorTimer::setNigtTimeToNow(), SensorTimer::setSurelySleptTime(), signalHandler(), CppTimer::startms(), SensorTimer::stopNew(), and usage().
signalHandler()
void signalHandler (int signum)
Definition at line 100 of file main.cpp.
{
     g_running = 0;
     printf("\n\n\nProgram Terminated\n\n\n");
 }
References g_running.
Referenced by main().
usage()
void usage (void)
Definition at line 105 of file main.cpp.
                 {
     printf("\nUsage:\n"
                  "./main [-h] for usage\n"
                  "./main [-t <int>] to put bpm threshold\n"
                  "./main [-g <bool>] 1 to plot in qtplot. Default: 1\n"
                  "./main [-l <bool>] 1 to play audio locally. Default: 1\n"
                  "./main [-n <bool>] 1 to set night time to now. Default: 0\n"
                  "./main [-w <int> ]set waiting time to confirm sleep.\n"
                  "./main [-s <bool>] 1 for simulated bpm. Default: 0\n");
 }
Referenced by main().
Variable Documentation
g_running
volatile int g_running = 1
Definition at line 98 of file main.cpp.
Referenced by main(), and signalHandler().